name: build-and-test
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build -DBUILD_TESTING=ON
      - name: Build
        run: cmake --build build --config Release -- -j 2
      - name: Test
        run: ctest --test-dir build --output-on-failure
