name: build-and-test
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build -DBUILD_TESTING=ON
      - name: Build
        run: cmake --build build --config Release -- -j 2
      - name: Test
        run: ctest --test-dir build --output-on-failure
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-tidy
        run: clang-tidy src/*.cpp -- -std=c++17
